# Generated by Django 5.2 on 2025-04-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0009_remove_order_created_at_remove_order_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
