# Generated by Django 5.2 on 2025-05-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0013_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
