# Generated by Django 5.2 on 2025-05-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0015_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
    ]
