# Generated by Django 5.2 on 2025-05-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0016_rename_order_orderitem_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
